### ISSUE TITLE
Cutoff function 16: GenerateCarbonProperties

### ISSUE THREAD

**Issue by cmutel** [OcelotProject/Ocelot#26]
If a dataset has information about carbon content, this task generates any missing properties for carbon, e. g. biogenic and fossil content.

**Comment by cmutel** [comment]
@ecoinvent How can you determine the split between biogenic and fossil content if not provided in the dataset?

**Comment by ecoinvent** [comment]
@cmutel Do you have a dataset as an example?  Carbon content fossil and non-fossil is a mandatory property, it should be there.

**Comment by cmutel** [comment]
This is a direct quote from the technical documentation, I am just trying to figure out what it means :) 

You are right, these are present in all exchanges with properties in 3.2. Is there a complete list of required properties? Are all of `dry mass`, `water in wet mass`, `water content`, and `wet mass` also required?

**Comment by ecoinvent** [comment]
@cmutel Yes, 6 mandatory properties: dry mass, water in wet mass, water content, wet mass, carbon content fossil and carbon content non fossil.  This is true, except for energy and infrastructures.

**Comment by cmutel** [comment]
Will be closed in PR #64.
