### ISSUE TITLE
Is the current logging structure optimal?

### ISSUE THREAD

**Issue by cmutel** [OcelotProject/Ocelot#3]
We currently write logs designed to be consumed directly by the HTML report generator. To do this, we just serialize and write lines of JSON. However, we might want other logs, or other types of logs. Some libraries to consider:

* [structlog](http://structlog.readthedocs.io/en/stable/getting-started.html)
* [python-json-logger](https://github.com/madzak/python-json-logger)

**Comment by ecoinvent** [comment]
I like the structlog.  For now, I’m just writing logs in csv to understand what I’m doing.  Next time I write a logger, I’ll give a try to structlog.  

You’ll find attached my post about priorities.  

You need a call soon?  I’m still working on allocation.  I’m running into trouble with the odd cases.  I’ll have to question Ingo, but on my side, I can keep working without your input for a while.  

G

**Comment by cmutel** [comment]
The current structure is well integrated with logger and HTML report generator.
