### ISSUE TITLE
stuck at installation

### ISSUE THREAD

**Issue by smsmetana** [OcelotProject/Ocelot#69]
I am not sure if this is the right spot to discuss but I am trying to install Ocelot on Phyton the way described here: 
https://docs.ocelot.space/installation.html

I am stuck at line 3:
activate ocelot
conda install -y pywin32
pip install --no-cache-dir git+https://github.com/OcelotProject/Ocelot.git#egg=ocelot

My command generate the error of cloning the command git clone -q [winerror 2]
And not finding the command git

Well I tried the same but without the git command and it tried to collect the ocelot from the address and then generated the number of trials and errors... Whole list, which I cannot copy from my command.

I assume it didn't work, as the command ocelot-cli --help does not work... 

Possible solutions?

Thank you
Sergiy Smetana

**Comment by cmutel** [comment]
Installation docs changed in 746272376eca9fc0cc787c9920a6c021340837a9 to not require git. See if the [new docs](https://docs.ocelot.space/installation.html) work any better!

**Comment by smsmetana** [comment]
Thanks. Works now.

**Comment by cmutel** [comment]
Fixed in 746272376eca9fc0cc787c9920a6c021340837a9.
