### ISSUE TITLE
ecospold2 or Error run out of input

### ISSUE THREAD

**Issue by smsmetana** [OcelotProject/Ocelot#72]
Hello again. Trying to play a bit with Ocelot. 

It is stated: "To run Ocelot, you will need an unlinked database in ecospold2 format." What does it actually mean an unlinked? separately downloaded from Ecoinvent or kind of blank?

Anyway I tried to use Wheat Production DE ecosplod files and seems after some thinking Ocelot just generated a few trials to extract and so on, but finally Error run out of inputs. 

I tried to leave only one Ecospold2 file and then the model run was not able to find a connection to some processes: OSError: [Winerror 87] False parameter

Is it because the Ocelot under construction or because ecospold files are "linked"

Thanks.

**Comment by cmutel** [comment]
Fixed in summer school :) Need unlinked files which need to be requested specially from ecoinvent centre or developed on your own.

**Comment by cmutel** [comment]
Fixed in summer school :) Need unlinked files which need to be requested specially from ecoinvent centre or developed on your own.
